{
 "title": "Nvidia GPU Metrics (utkuozdemir)",
 "description": "Nvidia GPU Metrics based on the prometheus metrics from github.com/utkuozdemir/nvidia_gpu_exporter",
 "tags": [
  "nvidia",
  "nvidia-smi",
  "nvidia_gpu_exporter",
  "prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "gpu",
    "label": "GPU",
    "query": {
     "query": "label_values(nvidia_smi_index, uuid)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Name",
   "type": "stat",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nvidia_smi_index{uuid=\"$gpu\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Utilization %",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nvidia_smi_utilization_gpu_ratio{uuid=\"$gpu\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "Memory Utilization %",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nvidia_smi_utilization_memory_ratio{uuid=\"$gpu\"}"
    }
   ]
  },
  {
   "title": "Fan Speed %",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nvidia_smi_fan_speed_ratio{uuid=\"$gpu\"}"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nvidia_smi_temperature_gpu{uuid=\"$gpu\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "Clock Speed",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "expr": "nvidia_smi_clocks_current_graphics_clock_hz{uuid=\"$gpu\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "Driver Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nvidia_smi_driver_version{uuid=\"$gpu\"}"
    }
   ]
  },
  {
   "title": "P-State",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "prefix:P" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nvidia_smi_pstate{uuid=\"$gpu\"}"
    }
   ]
  },
  {
   "title": "Clock Speed %",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nvidia_smi_clocks_current_graphics_clock_hz{uuid=\"$gpu\"} / nvidia_smi_clocks_max_graphics_clock_hz{uuid=\"$gpu\"}"
    }
   ]
  },
  {
   "title": "Power Draw %",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nvidia_smi_power_draw_watts{uuid=\"$gpu\"} / nvidia_smi_power_limit_watts{uuid=\"$gpu\"}"
    }
   ]
  },
  {
   "title": "Memory Utilization %",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "nvidia_smi_utilization_memory_ratio{uuid=\"$gpu\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "Fan Speed %",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "nvidia_smi_fan_speed_ratio{uuid=\"$gpu\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "GPU Utilization %",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "nvidia_smi_utilization_gpu_ratio{uuid=\"$gpu\"}"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "nvidia_smi_temperature_gpu{uuid=\"$gpu\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "Video Clock Speed",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "expr": "nvidia_smi_clocks_current_video_clock_hz{uuid=\"$gpu\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "Power Draw",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "nvidia_smi_power_draw_watts{uuid=\"$gpu\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "Memory Clock Speed",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "expr": "nvidia_smi_clocks_current_memory_clock_hz{uuid=\"$gpu\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "nvidia_smi_memory_used_bytes{uuid=\"$gpu\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  }
 ]
}