{
 "title": "Locust Prometheus Monitoring Modern",
 "description": "Locust Dashboard for load test analysis",
 "tags": [
  "locust",
  "prometheus"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "Main", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Locust Status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "locust_state", "legendFormat": "{{state}}" }
   ]
  },
  {
   "title": "Swarmed users",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "locust_user_count" }
   ]
  },
  {
   "title": "Current RPS",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "locust_total_rps" }
   ]
  },
  {
   "title": "Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(locust_requests_num_requests{method=~\".+\"})"
    }
   ]
  },
  {
   "title": "Fails",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "locust_fail_ratio" }
   ]
  },
  {
   "title": "Connected workers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "locust_workers" }
   ]
  },
  {
   "title": "Failures",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(locust_requests_num_failures{method=~\".+\"})"
    }
   ]
  },
  {
   "title": "Aggregate Report",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(locust_requests_ninetieth_response_time{method=~\".+\"}) by (method, name)"
    },
    {
     "expr": "sum(locust_requests_ninety_ninth_response_time{method=~\".+\"}) by (method, name)"
    },
    {
     "expr": "sum(locust_requests_min_response_time{method=~\".+\"}) by (method, name)"
    },
    {
     "expr": "sum(locust_requests_max_response_time{method=~\".+\"}) by (method, name)"
    },
    {
     "expr": "sum(locust_requests_avg_response_time{method=~\".+\"}) by (method, name)"
    },
    {
     "expr": "sum(locust_requests_median_response_time{method=~\".+\"}) by (method, name)"
    },
    {
     "expr": "sum(locust_requests_num_failures{method=~\".+\"}) by (method, name)"
    },
    {
     "expr": "sum(locust_requests_current_fail_per_sec{method=~\".+\"}) by (method, name)"
    },
    {
     "expr": "(sum(locust_requests_num_failures{method=~\".+\"}) by (method, name))/(sum(locust_requests_num_requests{method=~\".+\"}) by (method, name))"
    },
    {
     "expr": "sum(locust_requests_num_requests{method=~\".+\"}) by (method, name)"
    },
    {
     "expr": "sum(locust_requests_avg_content_length{method=~\".+\"}) by (method, name)"
    },
    {
     "expr": "sum(locust_requests_current_rps{method=~\".+\"}) by (method, name)"
    }
   ]
  },
  {
   "title": "RPS (endpoints)",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "locust_requests_current_rps{method=~\".+\"}",
     "legendFormat": "{{ method}} - {{name}}"
    }
   ]
  },
  {
   "title": "Users and Total RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "locust_user_count", "legendFormat": "Users" },
    { "expr": "locust_total_rps", "legendFormat": "Current RPS" }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Errors Per Second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "sum(locust_requests_current_fail_per_sec{method=~\".+\"}) by (method, name)",
     "legendFormat": "{{method}} - {{name}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(locust_errors) by (method, name, error)"
    }
   ]
  },
  { "title": "Response Times", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "Response Times",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "locust_current_response_time_percentile_95",
     "legendFormat": "P95"
    },
    {
     "expr": "locust_current_response_time_percentile_50",
     "legendFormat": "P50"
    }
   ]
  },
  {
   "title": "Response Times (avarage for all requests)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(locust_requests_max_response_time{method=~\".+\"})",
     "legendFormat": "AVG MAX"
    },
    {
     "expr": "avg(locust_requests_min_response_time{method=~\".+\"})",
     "legendFormat": "AVG MIN"
    },
    {
     "expr": "avg(locust_requests_avg_response_time{method=~\".+\"})",
     "legendFormat": "AVG AVG"
    },
    {
     "expr": "avg(locust_requests_median_response_time{method=~\".+\"})",
     "legendFormat": "AVG MEDIAN"
    }
   ]
  },
  {
   "title": "Avarage Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "locust_requests_avg_response_time{method=~\".+\"}",
     "legendFormat": "{{method}} - {{name}}"
    }
   ]
  },
  {
   "title": "90 %ile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "locust_requests_ninetieth_response_time{method=~\".+\"}",
     "legendFormat": "{{method}} - {{name}}"
    }
   ]
  },
  {
   "title": "99 %ile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "locust_requests_ninety_ninth_response_time{method=~\".+\"}",
     "legendFormat": "{{method}} - {{name}}"
    }
   ]
  },
  { "title": "Workers and users", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 95 } },
  {
   "title": "Users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "locust_user_count", "legendFormat": "Users" }
   ]
  },
  {
   "title": "Workers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "locust_workers", "legendFormat": "Workers" }
   ]
  },
  {
   "title": "Workers Info",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 104 },
   "targets": [
    { "expr": "locust_workers_info", "legendFormat": "Workers" }
   ]
  }
 ]
}